name: CI-PHP-7

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v6
              with:
                  php_version: 7.2
            - name: tests
              run: vendor/bin/phpunit
            - name: php-cs-fixer
              run: vendor/bin/php-cs-fixer fix --dry-run
            - name: phpstan
              run: vendor/bin/phpstan analyze
